# Generated by Django 3.0.5 on 2020-05-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('price', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('available', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('subcategory', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
