# Generated by Django 3.0.5 on 2020-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
